// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class InvoiceDetails
{
    public int Id { get; set; }

    public string InvoiceNo { get; set; }

    public int? InvoiceHeaderId { get; set; }

    public int? ItemId { get; set; }

    public string Narration { get; set; }

    public decimal? Rate { get; set; }

    public int? Qty { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Taxpercent { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? Cgstpercent { get; set; }

    public decimal? Cgstamount { get; set; }

    public decimal? Sgstpercent { get; set; }

    public decimal? Sgstamount { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }

    public decimal? IgstPercent { get; set; }

    public virtual InvoiceHeader InvoiceHeader { get; set; }

    public virtual ItemMaster Item { get; set; }
}