// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class InvoiceHeader
{
    public int Id { get; set; }

    public int? EntityId { get; set; }

    public int? PatientId { get; set; }

    public DateTime? AdmissionDate { get; set; }

    public DateTime? DischargeDate { get; set; }

    public string Opdipdno { get; set; }

    public decimal? Netamount { get; set; }

    public int? TotalQty { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? FinalAmount { get; set; }

    public decimal? PaidAmount { get; set; }

    public decimal? Balance { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }

    public bool? IsAdvanceAplicable { get; set; }

    public virtual EntityMaster Entity { get; set; }

    public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; } = new List<InvoiceDetails>();

    public virtual ICollection<InvoicePaymentDetails> InvoicePaymentDetails { get; set; } = new List<InvoicePaymentDetails>();

    public virtual PatientMaster Patient { get; set; }
}