// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class PatientMaster
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string State { get; set; }

    public string District { get; set; }

    public string PostalCode { get; set; }

    public string MobileNo { get; set; }

    public string ContactNo { get; set; }

    public string EmailId { get; set; }

    public string EmergencyPersonName { get; set; }

    public string EmergencyMobileNo { get; set; }

    public string EmergencyEmailId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<AdvanceMaster> AdvanceMaster { get; set; } = new List<AdvanceMaster>();

    public virtual ICollection<InvoiceHeader> InvoiceHeader { get; set; } = new List<InvoiceHeader>();
}