// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class PaymentMode
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }

    public bool? IsSelected { get; set; }

    public virtual ICollection<InvoicePaymentDetails> InvoicePaymentDetails { get; set; } = new List<InvoicePaymentDetails>();
}